### ISSUE TITLE
Multiple "index" filenames not supported?

### ISSUE THREAD

**Issue by extractachris** [bryanbraun/middleman-navtree#11]
I have multiple files named `index.html.erb` that act as directory indexes for various folders throughout my site.

I noticed NavTree incorrectly associated my site's root `index.html.erb` with `/work/client-1/index.erb.html` below and then skips every other folder that uses that same file name:

```
---
index.html.erb: /work/client-1/index.html.erb
contact: {}
documentation:
  defaults.html.erb: /documentation/defaults.html.erb
  partials:
    _head.erb: /documentation/partials/_head.erb
    _modules_nav.erb: /documentation/partials/_modules_nav.erb
favicon.ico: /favicon.ico
modules:
  contact_card.erb: /modules/contact_card.erb
  copy_block.erb: /modules/copy_block.erb
  featured_media.erb: /modules/featured_media.erb
resume: {}
work:
  client-2:
    project-a: {}
  client-3:
    project-b: {}
  client-4:
    project-c: {}
  client-1:
    project-d: {}
    project-e: {}
```
