### ISSUE TITLE
The titles of folders are not displayed

### ISSUE THREAD

**Issue by pyrog** [bryanbraun/middleman-navtree#8]
index.md are not associated with the parent folder to display his name (and eventually a content)

The following tree is generated:
```yaml
fr:
  beginner:
    index.md: /fr/beginner/index.md
    1-introduction.md: /fr/beginner/1-introduction.md
    …
  intermediate:
    index.md: /fr/intermediate/index.md
    edit-in-detail-osm.md: /fr/intermediate/edit-in-detail-osm.md
```
… with the following html:
```
Beginner
  Guide du débutant
  Introduction
  …
Intermediate
  Guides intermédiaires
  Edition avancée
```

But it should generate:
```yaml
fr:
  beginner: /fr/beginner/index.md
    1-introduction.md: /fr/beginner/1-introduction.md
    …
  intermediate: /fr/intermediate/index.md
    edit-in-detail-osm.md: /fr/intermediate/edit-in-detail-osm.md
```
… with the following html:
```
Guide du débutant
  Introduction
  …
Guides intermédiaires
  Edition avancée
```
